name: Build and Push Images
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_TAG: ${{ github.sha }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR login server
        id: acr
        run: |
          echo "LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)" >> $GITHUB_OUTPUT

      - name: ACR login for Docker
        run: az acr login -n $ACR_NAME

      - name: Build and push
        env:
          LOGIN_SERVER: ${{ steps.acr.outputs.LOGIN_SERVER }}
        run: |
          docker build -f IaC/Dockerfile.api -t $LOGIN_SERVER/dp-stock-api:$IMAGE_TAG .
          docker build -f IaC/Dockerfile.agent -t $LOGIN_SERVER/dp-stock-agent:$IMAGE_TAG .
          docker build -f frontend/Dockerfile -t $LOGIN_SERVER/dp-stock-frontend:$IMAGE_TAG .
          docker push $LOGIN_SERVER/dp-stock-api:$IMAGE_TAG
          docker push $LOGIN_SERVER/dp-stock-agent:$IMAGE_TAG
          docker push $LOGIN_SERVER/dp-stock-frontend:$IMAGE_TAG

      - name: Publish image tags artifact
        run: |
          echo "${{ steps.acr.outputs.LOGIN_SERVER }}/dp-stock-api:${IMAGE_TAG}"   >> images.txt
          echo "${{ steps.acr.outputs.LOGIN_SERVER }}/dp-stock-agent:${IMAGE_TAG}" >> images.txt
          echo "${{ steps.acr.outputs.LOGIN_SERVER }}/dp-stock-frontend:${IMAGE_TAG}" >> images.txt
          echo "::notice title=Images::$(cat images.txt | tr '\n' ' ')"