name: PR CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Backend deps and tests
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && python -m pip install -r requirements.txt || true
          python -m pip install pytest || true
          pytest -q || echo "No tests or tests skipped"

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm', cache-dependency-path: 'frontend/package-lock.json' }
      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Docker build (no push)
        run: |
          docker build -f IaC/Dockerfile.api -t dp-stock/api:pr-${{ github.sha }} .
          docker build -f IaC/Dockerfile.agent -t dp-stock/agent:pr-${{ github.sha }} .
          docker build -f frontend/Dockerfile -t dp-stock/frontend:pr-${{ github.sha }} .